name: neobrutalism_theme
description: A list of widget in Neubrutalism style.
version: 0.0.1
repository: https://github.com/FrancescoPenasa/neubrutalism_package
homepage: francescoPenasa.github.io

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: null