name: neubrutalism_theme
description: Simple widget collection in Neubrutalism style with different types of animations with the goal of simplify Widget usage.
version: 0.0.1
repository: https://github.com/FrancescoPenasa/neubrutalism_package
homepage: https://francescopenasa.github.io/
publish_to: https://pub.dev/packages/neubrutalism_theme
environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: null